---
description: >
  Default executor for testdino orb using Node.js Docker image.
  This executor provides a Node.js environment required for running
  the TestDino CLI (tdpw).

docker:
  - image: 'cimg/node:<<parameters.tag>>'

parameters:
  tag:
    default: lts
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
